export const HTTPS_STATUS_AND_CODE = {
	OK: {
		STATUS: 200,
		CODE: 'OK',
	},
	CREATED: {
		STATUS: 201,
		CODE: 'CREATED',
	},
	ACCEPTED: {
		STATUS: 202,
		CODE: 'ACCEPTED',
	},
	MOVED_PERMANENTLY: {
		STATUS: 301,
		CODE: 'MOVE_PERMANENTLY',
	},
	FOUND: {
		STATUS: 302,
		CODE: 'FOUND',
	},
	BAD_REQUEST: {
		STATUS: 400,
		CODE: 'BAD_REQUEST',
	},
	UNAUTHORIZED: {
		STATUS: 401,
		CODE: 'UNAUTHORIZED',
	},
	FORBIDDEN: {
		STATUS: 403,
		CODE: 'FORBIDDEN',
	},
	NOT_FOUND: {
		STATUS: 404,
		CODE: 'NOT_FOUND',
	},
	UNSUPPORTED_MEDIA_TYPE: {
		STATUS: 415,
		CODE: 'UNSUPPORTED_MEDIA_TYPE',
	},
	INTERNAL_SERVER_ERROR: {
		STATUS: 500,
		CODE: 'INTERNAL_SERVER_ERROR',
	},
} as const;